### ISSUE TITLE
Short hand SVG paths aren't parsed correctly

### ISSUE THREAD

**Issue by kkaefer** [kfitfk/svg-boundings#2]
The parser seems to have trouble parsing this SVG path: 

```
M8.52 13.763L11.7 10.58l.495.495-3.181 3.182z
```

The problem seems to be with correctly separating the numbers from the `l.495.495-3.181 3.182` command, in particular the lack of a space between the first `.495` and the second `.495`.

**Comment by kfitfk** [comment]
Ah, I didn't notice that the numbers could be set like this. I'll fix this in the next few days.

**Comment by kfitfk** [comment]
Fixed in dfc08291b22044410a0d72fa504d3ea2719df92f
