### ISSUE TITLE
Support for transforms on all element types

### ISSUE THREAD

**Issue by shaunco** [kfitfk/svg-boundings#4]
Great library!

Currently transforms are only supported on rect, circle, and ellipse. I tried adding this to the end of `boundingRectOfPath` (just before the existing return):
```js
  var transform = path.transform;
  var matrix;
  if (transform) {
    matrix = Helper.matrixStrToObj(transform);
    return Helper.boundingUnderTransform(matrix, t, r, b, l);
  }
```

along with changing `elementObject` to include the `transform` attribute from `path` elements.

it seemed to properly calculate the transformed path, but doesn't seem to obey `shouldReturnTrueBounding=true`.

It would be great to have transform support for all svg element type.

**Comment by kfitfk** [comment]
If the `<path />` element has a `transform` attribute, the following steps won't return the correct bounding box:

1. calculate the bounding box using points specified by `d` attribute while ignoring the `transform` attribute;
2. use `Helper.boundingUnderTransform` to get a new value for result from Step 1.

I think the transform should be applied to all points specified by the `d` first. I'll try to update this later this week.

**Comment by kfitfk** [comment]
@shaunco Please try 2.0.7

![svg-boundings 2.0.7 vs. getBoundingClientRect](https://user-images.githubusercontent.com/2555626/154806677-e0b7e2d7-fbb5-4017-b6ae-9519b58bea7b.png)
